[[agents]]
id = "test_agent1"
name = "HoloTester1"
public_address = "HcScjcgKqXC5pmfvka9DmtEJwVr548yd86UPtJGGoue9ynuikuRTN7oE5zcjgbi"
keystore_file = "./agent1.keystore"

[[dnas]]
id = "chat_dna"
file = "./dna/hylo.dna.json"
hash = "Qm328wyq38924y"

[[instances]]
id = "hylo-chat"
dna = "chat_dna"
agent = "test_agent1"
[instances.logger]
type = "simple"
file = "app_spec.log"
[instances.storage]
type = "memory"
path = "tmp-storage"

[[interfaces]]
id = "websocket_interface"
[interfaces.driver]
type = "websocket"
port = 3401
[[interfaces.instances]]
id = "hylo-chat"

[[interfaces]]
id = "GraphiQl-http-interface"
[interfaces.driver]
type = "http"
port = 4001
[[interfaces.instances]]
id = "hylo-chat"


#===================================================================

[[ui_bundles]]
id = "main"
root_dir = "./ui/build"
hash = "Qm000"

[[ui_interfaces]]
id = "ui-interface"
bundle = "main"
port = 5001
dna_interface = "GraphiQl-http-interface"

# [logger]
# type="debug"
# [[logger.rules.rules]]
# exclude=true
# pattern=".*"

[network]
n3h_path = "/path/to/n3h"
n3h_persistence_path = "/tmp"
bootstrap_nodes = []
n3h_log_level = "t"
