[[agents]]
id = "hylo_agent"
name = "HoloTester2"
public_address = "HcScidPSdAT43q9qirJwt5rHJYjjsvougV3jgSBwdJujszw3bBu5Mktr74Rgnea"
keystore_file = "./agent2.keystore"

[[dnas]]
id = "chat_dna"
file = "./dna/hylo.dna.json"
hash = "Qm328wyq38924y"

[[instances]]
id = "hylo-chat"
dna = "chat_dna"
agent = "hylo_agent"
[instances.logger]
type = "simple"
file = "app_spec.log"
[instances.storage]
type = "memory"
path = "tmp-storage"

# -- WS-RPC interface to Hylo DNA

[[interfaces]]
id = "websocket_interface"
[interfaces.driver]
type = "websocket"
port = 3402
[[interfaces.instances]]
id = "hylo-chat"

# # -- Hylo UI

# [[ui_bundles]]
# id = "hylo-ui"
# root_dir = "./hylo-ui"
# hash = "Qm000"

# [[ui_interfaces]]
# id = "hylo-interface"
# bundle = "hylo-ui"
# port = 8000

# -- GraphiQl HTTP interface and UI

[[interfaces]]
id = "GraphiQl-http-interface"
[interfaces.driver]
type = "http"
port = 4002
[[interfaces.instances]]
id = "hylo-chat"

[[ui_bundles]]
id = "main"
root_dir = "./ui/build"
hash = "Qm000"

[[ui_interfaces]]
id = "ui-interface"
bundle = "main"
port = 5002
dna_interface = "GraphiQl-http-interface"

# -- Networking

[network]
n3h_path = "/path/to/n3h"
n3h_persistence_path = "/tmp"
n3h_log_level = "t"
bootstrap_nodes = []
# * For testing with a persistent n3h bootstrap node:
# bootstrap_nodes = [
#   "wss://holo-dna.hylo.com:38474/?a=HcSci3mbfjh4nqtj7rQArggU7Ijrv6dbqT9fwpTmUQsthb84DQDPgTvayg6iuti"
# ]

# -- Logger (settings below will disable most logging)

# [logger]
# type="debug"
# [[logger.rules.rules]]
# exclude=true
# pattern=".*"
